### ISSUE TITLE
support multi-value values for properties

### ISSUE THREAD

**Issue by joeferner** [lumifyio/lumify#461]
For example....

If I have a name property I would like it to be broken down into first and last name but under a single name heading.  When editing the property allow both first and last to be edited together.

I think we can do this using the property key.  So the property name will be first name and last name but the property key will be the same for both properties.

Backend Todo
* [x] Add example compound property with these new lumify attributes
    * [x] dependent fields: IRI's of properties
    * [x] display formula: function will get access to all dependent properties and return a display string
    * [x] validation formula: function will return true/false based on the values of dependent properties
* [x] Update VertexSetProperty route to take multiple property values at a time (with one visibility and justification for all)
* [x] Update VertexPropertyDelete route to accept a compound property field (dev#name) and key – then delete all dependents, or accept multiple names (dev#first, dev#last) and key – and delete them

Frontend Todo
* [x] Enhance add property form to show all dependent fields to edit
* [x] Apply validation rules based on ontology formula
* [x] Use new route to save multiple properties
* [x] Display compound property correctly based on display formula and have it update when any dependent fields are changed
* [x] Fix edit form for compound fields
* [x] Fix edit form to show all properties previous values (edit instead) if adding
* [x] Hide dependent fields in place of compound field in property display
* [x] Allow search filtering using compound and dependent fields
* [x] Make diff panel show the compound properties (not dependents)
* [x] Show compound properties in multiple selection pane (not dependents)
* [x] Allow deleting of compound properties (that delete the dependents)

**Comment by jharwig** [comment]
Frontend Todo
* [ ] Enhance add property form to show all dependent fields to edit
* [ ] Apply validation rules based on ontology formula
* [ ] Use new route to save multiple properties
* [ ] Display compound property correctly based on display formula and have it update when any dependent fields are changed
* [ ] Fix edit form to show all properties previous values
* [ ] Hide dependent fields in place of compound field in property display
* [ ] Allow search filtering using compound and dependent fields

**Comment by jharwig** [comment]
VertexPropertyDelete with a compound property is throwing an exception about “Found multiple non public properties”
