### ISSUE TITLE
fronend build failes - PathFinding.js not found

### ISSUE THREAD

**Issue by mloepfe** [lumifyio/lumify#511]
the command  "mvn package -P web-war -pl web/war -am -DskipTests -Dsource.skip=true" fails with the error message:

    Running "bower:install" (bower) task
    Fatal error: Package PathFinding.js not found

If I just rerun the command I get an other error:

    Running "less:production" (less) task
    >> FileError: '../libs/bootstrap/less/bootstrap.less' wasn't found in less/lumify.less on line 27, column 1:

The configured package does not exists:

    $ bower info PathFinding.js
    bower                        ENOTFOUND Package PathFinding.js not found
 
    $ bower info PathFinding
    bower                        ENOTFOUND Package PathFinding not found

It seems the corresponding line in bower.json should be

    "pathfinding": "0.4.16"

instead of

    "PathFinding.js": "0.4.10"

My build environment is a OSX-10.10.1 with boot2docker vm

**Comment by jharwig** [comment]
Bower configuration was removed from the source repo, so switched to a git path/tag. The "pathfinding" repo is a stub repo pointing to the source, which I'd rather not use

**Comment by mloepfe** [comment]
Thanks for the very fast fix! It works:-)
