### ISSUE TITLE
"slower?" find path shows complete but doesn't show results

### ISSUE THREAD

**Issue by dsingley** [lumifyio/lumify#534]
you can see the results if you reload the page and open the activity pane

**Comment by dsingley** [comment]
exception at https://github.com/lumifyio/lumify/blob/master/core/core/src/main/java/io/lumify/core/model/longRunningProcess/LongRunningProcessRunner.java#L69

Failed to index ad2fce43370643188875bffc13eefe3f_http://lumify.io/longRunningProcess#queueItemJson_ (message: IllegalArgumentException[Document contains at least one immense term in field="http://lumify.io/longRunningProcess#queueItemJson_exactMatch" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[123, 34, 115, 116, 97, 114, 116, 84, 105, 109, 101, 34, 58, 49, 52, 50, 50, 52, 55, 48, 51, 57, 49, 57, 49, 51, 44, 34, 119, 111]...', original message: bytes can be at most 32766 in length; got 214307]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 214307]; )

**Comment by jharwig** [comment]
happens when the results are over some number (saw it with 50)
