### ISSUE TITLE
long running processes don't work in firefox

### ISSUE THREAD

**Issue by joeferner** [lumifyio/lumify#540]

**Comment by jharwig** [comment]
Which version? any errors? Works in Firefox 34 for me.

**Comment by joeferner** [comment]
35.0.1

No errors. The activity window pops up then nothing shows.

Logged in as same user in Chrome and the LRP kicked off because it shows up in the activity window in Chrome

**Comment by jharwig** [comment]
Updated firefox and saw same behavior as you the first load. But couldn't reproduce it after refresh (or multiple refreshes). Have to investigate more. Might be some issue with socket connection on some page loads

**Comment by jharwig** [comment]
Found some possible edge cases that could cause this.
