### ISSUE TITLE
Workspace filtering doesn't clear search result count

### ISSUE THREAD

**Issue by akeffalas** [lumifyio/lumify#595]
After running a workspace search query in the find panel the results count is displayed as expected.  Next, peform a global (lumify) query.  Then return to the workspace search query form and you'll see the search result count from the previous workspace query.

**Comment by jharwig** [comment]
If I am understanding correctly this is works as designed. the workspace query and lumify search are separate. They both have internal state that is persisted, each can have different filters, and queries active at the same time. Searching in lumify doesn't clear the workspace search, and vice versa.

**Comment by akeffalas** [comment]
Thanks for the explanation Jason.  I apologize for the hastily written description.  Based on what you said, this issue can likely be closed since it's "as designed".
