### ISSUE TITLE
https://try.lumify.io not working

### ISSUE THREAD

**Issue by Joshfindit** [lumifyio/lumify#672]
https://try.lumify.io comes up with a visually blank page.

Console reports

```
 Can't find variable: File
   (anonymous function)promise-6.0.0.js:355
```

Tested on:
OSX 10.11: Chrome Version `46.0.2490.80 (64-bit)`, Safari Version `9.0.1 (11601.2.7.2)`
Pingdom: http://tools.pingdom.com/fpt/#!/d39CPT/https://try.lumify.io

**Comment by LeonP92** [comment]
Hi Josh, thank you. We were in the works of moving try to a newer version. 

As part of the change, there is a clean up process that happens every week where all new data is wiped. Just to let you know.
