### ISSUE TITLE
Can't find Rabbitmq user and password in config file

### ISSUE THREAD

**Issue by ashitabh** [lumifyio/lumify#676]
I have setup Lumify using  RabbitMQ 3.6 , however I can't find any config setting to setup user and password for RabbitMQ. ( I want to use user "test" and password "test")

I am getting following error 
Error injecting constructor, com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
  at io.lumify.model.rabbitmq.RabbitMQWorkQueueRepository.<init>(RabbitMQWorkQueueRepository.java:32)
  while locating io.lumify.model.rabbitmq.RabbitMQWorkQueueRepository

Nowhere in documentation , I find bypassing authentication , Please help

**Comment by LeonP92** [comment]
You'll need to use the command line management tool, rabbitmqadmin, to add the user test. You can use the guest user (password guest) to start out with but there's no user test when installed. 

For more info on rabbitmqadmin's you can use the --help argument to see the usage. 
`rabbitmqadmin add_user test test` is probably the command you want.

**Comment by ashitabh** [comment]
i actually created a new user test/test , but anyway, guest/guest is working . thanks

**Comment by OnurSevket** [comment]
"**rabbitmqadmin add_user test test** " 'rabbitmqadmin' is not recognized as an internal or external command,
operable program or batch file
